language: ruby
sudo: true
cache: bundler
services:
  - postgresql
rvm:
 - 2.7.3
before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.3.deb
  - sudo dpkg -i --force-confnew elasticsearch-6.2.3.deb
  - sudo /etc/init.d/elasticsearch start
  - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1; done
  - bin/rake db:test:prepare
  - RAILS_ENV=test bin/rails larp_library:elasticsearch:setup
